name: Upload to PyPI

on:
  push:
    branches: ['main']
    paths: ["src/tictoc/__init__.py", ".github/workflows/*"]

jobs:
  push_to_pypi:
    name: Release to PyPI
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: |
          python3 -m pip install --upgrade build twine
          python3 -m build

      - name: Upload to tictoc PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: python3 -m twine upload dist/* -u '__token__' -p "$PYPI_TOKEN"
